name: ci-cd

on:
  push
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
    - name: Install dependencies
      run: npm ci --legacy-peer-deps --no-audit --force --verbose 
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
